/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk2_asteroids_mmo;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author patry
 */
public class LogIn extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        try {
            initComponents();
            setLocationRelativeTo(null);
            setResizable(false);
            logInPanel.setBackground(new Color(0, 0, 0, 170));
            setSize(806, 635);

            Color baseColor = new Color(127, 116, 70);
            File font_file = new File("Rebellion.otf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, font_file);
            Font titelLabelFont = font.deriveFont(60f);
            titelLabel.setFont(titelLabelFont);
            usernameTextField.setBackground(new Color(0, 0, 0, 170));
            usernameTextField.setForeground(baseColor);
            Border borderTextField = BorderFactory.createLineBorder(baseColor);
            usernameTextField.setBorder(borderTextField);
            Border borderButton = BorderFactory.createLineBorder(new Color(127, 116, 70, 0));
            logInButton.setBorder(borderButton);
            logInButton.setBackground(new Color(0, 0, 0, 255));
            logInButton.setForeground(baseColor);
            logInButton.setFocusable(false);
            Font buttonFont = font.deriveFont(24f);
            logInButton.setFont(buttonFont);
            exitButton.setBorder(borderButton);
            exitButton.setBackground(new Color(0, 0, 0, 255));
            exitButton.setForeground(baseColor);
            exitButton.setFocusable(false);
            exitButton.setFont(buttonFont);
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        titelLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        logInPanel = new javax.swing.JPanel();
        logInButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        backgroundButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATEROIDS");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        backgroundPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        backgroundPanel.setLayout(null);

        titelLabel.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        titelLabel.setForeground(new java.awt.Color(127, 116, 70));
        titelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titelLabel.setText("ASTEROIDS");
        backgroundPanel.add(titelLabel);
        titelLabel.setBounds(150, 25, 500, 90);

        exitButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        exitButton.setText("EXIT");
        backgroundPanel.add(exitButton);
        exitButton.setBounds(300, 510, 200, 40);

        logInButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        logInButton.setText("NEW GAME");
        logInButton.setVerifyInputWhenFocusTarget(false);
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(127, 116, 70));
        usernameLabel.setText("Username:");

        usernameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(255, 51, 51));
        usernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(logInButton)
                .addGap(30, 30, 30))
        );

        backgroundPanel.add(logInPanel);
        logInPanel.setBounds(150, 150, 500, 300);

        backgroundButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\patry\\Documents\\GitHub\\sk2_asteroids_mmo\\space_background.png")); // NOI18N
        backgroundPanel.add(backgroundButton);
        backgroundButton.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        EventQueue.invokeLater(() -> {
            Mmo ex = new Mmo(usernameTextField.getText());
            ex.setVisible(true);
        });
        dispose();
    }//GEN-LAST:event_logInButtonActionPerformed

    private void usernameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTextFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            EventQueue.invokeLater(() -> {
                Mmo ex = new Mmo(usernameTextField.getText());
                ex.setVisible(true);
            });
            dispose();
        }
    }//GEN-LAST:event_usernameTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton logInButton;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JLabel titelLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
